### ISSUE TITLE
Can't run anything on ARM 

### ISSUE THREAD

**Issue by petevine** [pcwalton/sprocketnes#21]
Tried twice with some random ROMS:

````
target/release/nes   MunchieAttack.nes 
Loaded ROM: PRG-ROM: 16 KB, CHR-ROM: 0 KB, Mapper: 0 (0), Trainer: false
thread '<main>' panicked at 'index out of bounds: the len is 0 but the index is 1', src/libcollections/vec.rs:1106
stack backtrace:
   1: 0xb6f837bb - sys::backtrace::tracing::imp::write::h86e39446169e67d0Wnt
   2: 0xb6f860cb - panicking::log_panic::_<closure>::closure.39676
   3: 0xb6f85aef - panicking::log_panic::h7e0ce1e7485944fbUpx
   4: 0xb6f7ae5f - sys_common::unwind::begin_unwind_inner::h1d39a3f983dfda740gs
   5: 0xb6f7b013 - sys_common::unwind::begin_unwind_fmt::h2f77b9962e7023ac6fs
   6: 0xb6f82d97 - rust_begin_unwind
   7: 0xb6f8c79f - panicking::panic_fmt::h48301c5acd531c5bZEK
   8: 0xb6f8c75b - panicking::panic_bounds_check::h8d31f567a438d4e15DK
   9: 0xb6f6bfc7 - mapper::_<impl>::chr_loadb::hb17d08e4fddb2e93FXd
  10: 0xb6f6d5e3 - ppu::_<impl>::step::h122e120144b10602frf
  11: 0xb6f6eb23 - start_emulator::ha09827b57096d9acNGf
  12: 0xb6f66437 - main::h4c1a5b6fa5311b62Qda
````

and

````
target/release/nes   SolarWars2001.NES
Loaded ROM: PRG-ROM: 32 KB, CHR-ROM: 32 KB, Mapper: 3 (3), Trainer: false
thread '<main>' panicked at 'unsupported mapper', src/mapper.rs:35
stack backtrace:
   1: 0xb6f9b7bb - sys::backtrace::tracing::imp::write::h86e39446169e67d0Wnt
   2: 0xb6f9e0cb - panicking::log_panic::_<closure>::closure.39676
   3: 0xb6f9daef - panicking::log_panic::h7e0ce1e7485944fbUpx
   4: 0xb6f92e5f - sys_common::unwind::begin_unwind_inner::h1d39a3f983dfda740gs
   5: 0xb6f803df - sys_common::unwind::begin_unwind::begin_unwind::h3512061288630715681
   6: 0xb6f83d63 - mapper::create_mapper::he15687723fbb39d4uVd
   7: 0xb6f86717 - start_emulator::ha09827b57096d9acNGf
   8: 0xb6f7e437 - main::h4c1a5b6fa5311b62Qda
````

Compiled with 1.5, run at 16bpp colour depth.
I think README.md might need more info on requirements :)

**Comment by jonas-schievink** [comment]
I don't think this is related to ARM. The first crash is a bug that might even be fixed in my fork, but I have to check. The second crash happens because mapper 3 isn't implemented yet.

Can you try with Super Mario Bros.? It's one of the games that run pretty well.

**Comment by petevine** [comment]
Ah yes, at last something does work! Thx
